[package]
name = "rust"
version = "0.1.0"
authors = ["brian <bperrett@fusionbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
cached = "0.22.0"
